# Generated by Django 5.1.2 on 2024-11-03 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_interview_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('respondent_name', models.CharField(blank=True, max_length=200)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='main.interview')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('respondent_name', models.CharField(blank=True, max_length=200)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='main.questionnaire')),
            ],
        ),
    ]
